[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = [
    "aarch64-apple-darwin",
    "aarch64-unknown-linux-gnu",
    # # ARM windows runner doesn't have rust installed...
    # "aarch64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = false
# Uncomment to test full multi-platform release build and upload in pull request CI
# Which actions to run on pull requests.
pr-run-mode = "upload"


# Hacking around to avoid deprecated `ubuntu-20.04` runner and avoid
# cross-compiling.
[dist.github-custom-runners]
global = "ubuntu-latest"
# # ARM windows runner doesn't have rust installed...
# [dist.github-custom-runners.aarch64-pc-windows-msvc]
# runner = "windows-11-arm"
[dist.github-custom-runners.x86_64-pc-windows-msvc]
runner = "windows-latest"
[dist.github-custom-runners.x86_64-unknown-linux-gnu]
runner = "ubuntu-22.04"
[dist.github-custom-runners.aarch64-unknown-linux-gnu]
runner = "ubuntu-22.04-arm"
